- name: "Installing golang"
  include_role:
    name: "vendor/gantsign.golang"
  vars:
    golang_version: "1.18.2"
    golang_gopath: "{{ go_path }}"

- name: "Setting up go paths"
  lineinfile:
    path: "{{ home_directory }}/.bash_modules/104.go.sh"
    line: "{{ item }}"
    create: "yes"
    mode: "600"
  loop:
    - "export GOROOT='{{ ansible_local.golang.general.home }}'"
    - "export GOPATH='{{ go_path }}'"
    - 'export PATH="$GOPATH/bin:$GOROOT/bin:$PATH"'
