#!/usr/bin/python3
import argparse
import logging
import os
import shlex
import subprocess
import sys
import textwrap


logger = logging.getLogger()


def main():
    args = parse_args()
    if args.verbose:
        logger.setLevel(
            {
                0: logging.ERROR,
                1: logging.INFO,
                2: logging.DEBUG,
            }[min(args.verbose, 2)]
        )

    install_tmux_configs(args.env)
    logger.info('tmux configs installed!')

    install_vim_configs()
    logger.info('vim configs installed!')

    install_bash_configs(args.env)
    logger.info('bash configs installed!')


def parse_args(argv=None):
    parser = argparse.ArgumentParser()

    parser.add_argument(
        'env',
        help=(
            'Each environment is slightly different. This specifies '
            'the host OS, so that it can install compatible configs.'
        ),
        choices=get_env_options(),
    )
    parser.add_argument(
        '-v',
        '--verbose',
        help='Configures verbosity of logs.',
        action='count',
    )

    return parser.parse_args()


def install_tmux_configs(env):
    """
    :type env: str
    :param env: specifies host OS
    """
    # Install configs
    content = 'source-file {}'.format(
        get_path('configs/common/tmux/tmux.conf')
    ) 

    env_specific_config = get_path('configs/env/{}/tmux.conf'.format(env))
    if os.path.isfile(env_specific_config):
        content += '\nsource-file {}'.format(env_specific_config)

    with open(os.path.expanduser('~/.tmux.conf'), 'w') as f:
        f.write(content)

    # Install plugins and custom scripts
    try:
        os.mkdir(os.path.expanduser('~/.tmux'))
    except OSError:
        pass

    force_create_symlink(
        get_path('configs/common/tmux/scripts'),
        os.path.expanduser('~/.tmux/scripts'),
    )

    git(
        'clone',
        'https://github.com/tmux-plugins/tpm',
        os.path.expanduser('~/.tmux/plugins/tpm'),
    )

    tmux_pane_id = os.environ.get('TMUX_PANE')
    if tmux_pane_id:
        subprocess.call(
            shlex.split(
                'tmux source-file {}'.format(
                    os.path.expanduser('~/.tmux.conf')
                ),
            )
        )
        subprocess.call(
            shlex.split(
                'tmux send-keys -t "{}" "{}" Enter'.format(
                    tmux_pane_id,
                    os.path.expanduser(
                        '~/.tmux/plugins/tpm/scripts/install_plugins.sh'
                    ),
                )
            )
        )
    else:
        subprocess.call(
            shlex.split(
                'tmux new-session "{}"'.format(
                    os.path.expanduser(
                        '~/.tmux/plugins/tpm/scripts/install_plugins.sh'
                    ),
                )
            )
        )


def install_vim_configs():
    # Install configs
    content = textwrap.dedent("""
        source {plugins}
        source {base}
        source {custom_functions}
    """)[1:].format(
        base=get_path('configs/common/vim/vimrc'),
        custom_functions=get_path('configs/common/vim/vim-functions.vim'),
        plugins=get_path('configs/common/vim/vim-plugins.vim'),
    )

    with open(os.path.expanduser('~/.vimrc'), 'w') as f:
        f.write(content)

    # Install plugins
    subprocess.call(
        [
            'curl',
            '--fail',       # fail silently, on error
            '--location',   # follow redirects
            '--create-dirs',

            '--output',
            os.path.expanduser('~/.vim/autoload/plug.vim'),

            'https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim',
        ],
        stderr=subprocess.DEVNULL,
    )
    subprocess.call('vim +PlugInstall +qall'.split())


def install_bash_configs(env):
    """
    :type env: str
    :param env: specifies host OS
    """
    # Install configs
    content = 'source {}'.format(
        get_path('configs/common/bash/bash_profile')
    )

    env_specific_config = get_path('configs/env/{}/bash_profile'.format(env))
    if os.path.isfile(env_specific_config):
        content += '\nsource {}'.format(env_specific_config)

    with open(os.path.expanduser('~/.bash_profile'), 'w') as f:
        f.write(content)


def get_env_options():
    for root, dirs, filenames in os.walk(get_path('configs/env')):
        return dirs


def git(*args):
    try:
        return subprocess.check_output(
            [
                'git',
                *args,
            ],
            stderr=subprocess.STDOUT,
        )
    except subprocess.CalledProcessError as e:
        logger.error(e.output.decode('utf-8').strip())


def force_create_symlink(src, dest):
    try:
        os.symlink(src, dest)
    except FileExistsError:
        os.remove(dest)
        os.symlink(src, dest)
 

def get_path(path_to_file):
    return os.path.abspath(
        os.path.join(
            __file__,
            '..',
            path_to_file,
        )
    )


if __name__ == '__main__':
    logger.handlers = []
    handler = logging.StreamHandler(sys.stderr)
    handler.setFormatter(
        logging.Formatter(
            '[%(levelname)s]\t%(message)s',
        )
    )
    logger.addHandler(handler)

    main()
