#!/bin/bash

# Check for coreutils, and patch appropriately.
if brew --prefix coreutils 1>/dev/null 2>/dev/null; then
    gnuToolsPath="$(brew --prefix coreutils)/libexec/gnubin"
    if isNotInPath "$gnuToolsPath"; then
        export PATH="$gnuToolsPath:$PATH"
    fi
    unset gnuToolsPath

    alias man='_() { local path="$(brew --prefix coreutils)/libexec/gnuman"; man -M $path $1 1>/dev/null 2>&1;  if [[ "$?" == 0 ]]; then man -M $path $1; else man $1; fi }; _'
fi

# Source: https://opensource.com/article/19/5/python-3-default-mac
if command -v pyenv 1>/dev/null 2>&1; then
    if isNotInPath "/.pyenv/shims"; then
        eval "$(pyenv init -)"
    fi
fi

alias shas256sum="shasum -a 256"
alias umount="diskutil unmount"
