#!/usr/bin/env python3
import argparse
import os
import subprocess
import sys


def main():
    args = parse_args()
    files_to_lint = set()
    for filename in args.filenames:
        if not filename.startswith('roles'):
            continue

        parent, child = os.path.split(filename)
        if not parent and child.splitext()[1] in {'.yaml', '.yml'}:
            # This handles top level configs (e.g. site.yaml)
            files_to_lint.add(filename)
            continue

        while parent != 'roles':
            parent, child = os.path.split(parent)

        files_to_lint.add(os.path.join(parent, child))

    if not files_to_lint:
        # Need to do this, otherwise will default to scanning everything.
        return 0

    try:
        subprocess.check_call([
            'ansible-lint',
            '--force-color',
            *files_to_lint,
        ])
        return 0
    except subprocess.CalledProcessError as e:
        return 1


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        'filenames',
        nargs='*',
        help='Files to lint.',
    )

    return parser.parse_args()


if __name__ == '__main__':
    sys.exit(main())
