- name: "Downloading raw nodeJS GPG key"
  become: "yes"
  ansible.builtin.get_url:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    dest: /usr/share/keyrings/nodesource.gpg.key
    mode: "600"
    force: true

- name: "Dearmor nodeJS GPG key"
  become: "yes"
  ansible.builtin.command: >-
      gpg \
        --output /usr/share/keyrings/nodesource.gpg \
        --dearmor /usr/share/keyrings/nodesource.gpg.key
  args:
    creates: /usr/share/keyrings/nodesource.gpg

- name: "Removing raw nodeJS apt key"
  become: "yes"
  ansible.builtin.file:
    path: /usr/share/keyrings/nodesource.gpg.key
    state: absent

- name: "Add nodeJS {{ node_version }}.x PPA for apt repo"
  become: "yes"
  ansible.builtin.apt_repository:
    # TODO: `focal` may need to be changed, depending on the OS.
    # See `DISTRO=` at https://deb.nodesource.com/setup_16.x
    repo: "deb [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_{{ node_version }}.x focal main"
    update_cache: "yes"

- name: "Install nodeJS"
  become: "yes"
  apt:
    update_cache: "yes"
    name: nodejs
    state: present

- name: "Installing yarn"
  become: "yes"
  npm:
    name: yarn
    state: present
    global: "yes"
