#!/bin/bash

# Colorful bash
export PS1="\[\033[36m\]\u\[\033[m\]@\[\033[32m\]\h:\[\033[33;1m\]\w\[\033[m\]\$ "
export CLICOLOR=1
export LSCOLORS=ExFxBxDxCxegedabagacad

# Default options (because, why wouldn't you?)
alias cp='rsync --progress'     # for progress bar
alias du='du --human-readable'
alias grep="grep --color"
alias jq='jq --indent 4 --sort-keys'
alias vim='vim -p'      # opens tabs if multiple files are passed in

# Quick Navigation
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."

# Unfortunately, BSD doesn't support long arguments (wtf), but
# this set of arguments should be cross-functional.
#   -G: --classify
#   -h: --human-readable
#   -I: --ignore
alias ls='ls --color -Fh -I "*.pyc"'
alias la='ls -lAh'
