""""""""""""""""""""""""
" This assumes Vim 7.4 "
""""""""""""""""""""""""

map <F5> :tabp<Enter>
map <F6> :tabn<Enter>
map ZA :qa!<Enter>
map ZS :wqa<Enter>
map SS :w<Enter>

" Select all
map <C-a> <ESC>ggVG<Enter>

" noexpandtab means don't replace tabs with spaces.
set tabstop=8 softtabstop=0 expandtab shiftwidth=4 smarttab
map RT :%s/\t/    /g
" RT for ReTab

" add colors in vim
syntax on
set colorcolumn=80
highlight Folded ctermbg=Black

colorscheme monokai
set background=dark

" split windows that actually make sense
set splitbelow
set splitright

" display line numbers in vim
set number

" show column / row number
set ruler

" Folding configs
set foldmethod=syntax   " because indent acts weird with empty lines
set nofoldenable        " so files won't open closed

" vimdiff
map ]q :diffg LO<Enter>
map ]w :diffg BA<Enter>
map ]e :diffg RE<Enter>

" Better searching
set incsearch
set hlsearch
