- include_tasks: install_MacOSX.yaml
  when: ansible_distribution == "MacOSX"

- include_tasks: install_Debian.yaml
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

- name: "Installing uq"
  command:
    cmd: "go install github.com/solarkennedy/uq@latest"
    creates: "{{ home_directory }}/.go/bin/uq"
  environment:
    # NOTE: This local variable is set by the `golang` role
    PATH: "{{ ansible_local.golang.general.home }}/bin:{{ ansible_env.PATH }}"

- name: "Adding default settings"
  lineinfile:
    path: "{{ home_directory }}/.bash_modules/853.jq.sh"
    line: "alias jq='jq --indent 4 --sort-keys'"
    state: present
    create: "yes"
    mode: "600"
